name: Run Selenium Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install selenium pytest

    - name: Install Chrome v116 and ChromeDriver v116
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip curl

        # Install Chrome v116
        wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/linux64/chrome-linux64.zip
        unzip chrome-linux64.zip
        sudo mv chrome-linux64 /opt/chrome
        sudo ln -s /opt/chrome/chrome /usr/bin/google-chrome

        # Install matching ChromeDriver v116
        wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    - name: Start local server
      run: |
        python -m http.server 8000 &
        sleep 3

    - name: Run tests
      run: |
        pytest tests/
