name: Run Selenium Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install selenium pytest

    - name: Install Google Chrome and matching ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip curl
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

        # Get installed Chrome version
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')

        # Get matching ChromeDriver download URL
        DRIVER_JSON="https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json"
        DRIVER_VERSION=$(curl -s $DRIVER_JSON | grep -B 1 "$CHROME_VERSION" | grep "version" | head -1 | cut -d '"' -f4)
        DRIVER_LINK=$(curl -s $DRIVER_JSON | grep -A 20 "$DRIVER_VERSION" | grep "chromedriver-linux64.zip" | cut -d '"' -f4 | head -1)

        # Download and install ChromeDriver
        wget $DRIVER_LINK -O chromedriver.zip
        unzip chromedriver.zip
        sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    - name: Start local server
      run: |
        python -m http.server 8000 &
        sleep 3

    - name: Run tests
      run: |
        pytest tests/
